# Generated by Django 2.1 on 2018-08-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0003_auto_20180820_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minesweepergame',
            name='_game_state',
            field=models.TextField(blank=True),
        ),
    ]
