# Generated by Django 2.1 on 2018-08-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0002_auto_20180820_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='minesweepergame',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=4),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6),
        ),
    ]
